In [1]:
import numpy as np

In [7]:
old_alignment_c2i = np.load('../results/intermediate_steps/feature_alignment/coef_captions_to_images.npy')
new_alignment_c2i = np.load('../results/alignment/layer_8/coef_captions_to_images.npy')

In [8]:
old_alignment_c2i.shape

(768, 768)

In [9]:
old_alignment_c2i[:10]

array([[-0.06586116, -0.06584057, -0.04302067, ..., -0.01710376,
        -0.08587756,  0.0572179 ],
       [ 0.14582579,  0.02596512,  0.00644932, ...,  0.01360619,
         0.05304498,  0.01532002],
       [ 0.06558589, -0.04621033, -0.00599497, ...,  0.01173498,
        -0.01863663, -0.00616143],
       ...,
       [-0.01791775,  0.03866625,  0.01897837, ..., -0.11040347,
         0.00224039, -0.04789043],
       [ 0.0073558 , -0.00182424, -0.00094781, ...,  0.00798753,
         0.00148184,  0.00200871],
       [-0.00164205, -0.11017035,  0.05369824, ..., -0.07911264,
        -0.00051936, -0.05529642]])

In [10]:
new_alignment_c2i.shape

(768, 768)

In [11]:
new_alignment_c2i[:10]

array([[-0.03529627,  0.11066092,  0.04772103, ..., -0.01884992,
        -0.02981584,  0.01745446],
       [-0.03637606, -0.03687125, -0.03235766, ..., -0.02853437,
        -0.04265821, -0.01794142],
       [-0.0306418 ,  0.00069299, -0.00403774, ..., -0.02200768,
         0.01835931, -0.00550605],
       ...,
       [ 0.04132035,  0.07130297,  0.02376009, ..., -0.04732241,
        -0.02246874,  0.0541233 ],
       [-0.01079342,  0.01507477,  0.08916973, ..., -0.00705928,
         0.04118067, -0.03254234],
       [ 0.05301312, -0.04084847, -0.1064562 , ..., -0.06169366,
        -0.0202154 ,  0.00289513]], dtype=float32)

In [12]:
old_alignment_c2i == new_alignment_c2i

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [15]:
old_alignment_i2c = np.load('../results/intermediate_steps/feature_alignment/coef_images_to_captions.npy')
new_alignment_i2c = np.load('../results/alignment/layer_8/coef_images_to_captions.npy')

In [16]:
test_i2c = old_alignment_i2c == new_alignment_i2c
test_i2c.all()

False

In [17]:
old_alignment_i2c == new_alignment_i2c.T

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])